version: '3.8'

services:
  app:
    build:
      context: ./
    container_name: gosample_app
    ports: 
      - 10000:10000
    depends_on:
      - db

  db:
    platform: linux/x86_64 # fix issue on M1 Apple
    image: mysql:5.7
    container_name: gosample_db
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 10002:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysqldata:
    driver: local
