
CREATE TABLE IF NOT EXISTS `items`(
  `id` INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total_stock_value` INTEGER UNSIGNED NOT NULL,
  `current_stock_value` INTEGER UNSIGNED NOT NULL,
  `selling_price` DECIMAL(13, 2) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS `purchases`(
  `id` INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `item_id` INTEGER UNSIGNED NOT NULL,
  `quantity` INTEGER UNSIGNED NOT NULL,

  CONSTRAINT `fk_purchase_item_id` FOREIGN KEY(`item_id`) REFERENCES items(`id`)
)

